/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SEVEN_reg.h"
#include "SEVEN_DP_aliases.h"
#include "SEVEN_DP.h"
#include "SEVEN_G_aliases.h"
#include "SEVEN_G.h"
#include "SEVEN_F_aliases.h"
#include "SEVEN_F.h"
#include "SEVEN_E_aliases.h"
#include "SEVEN_E.h"
#include "SEVEN_D_aliases.h"
#include "SEVEN_D.h"
#include "SEVEN_C_aliases.h"
#include "SEVEN_C.h"
#include "SEVEN_B_aliases.h"
#include "SEVEN_B.h"
#include "SEVEN_A_aliases.h"
#include "SEVEN_A.h"
#include "UART_LOG.h"
#include "SEVEN_SELECT_aliases.h"
#include "SEVEN_SELECT.h"
#include "Button_1_aliases.h"
#include "Button_1.h"
#include "Button_2_aliases.h"
#include "Button_2.h"
#include "isr_Button.h"
#include "Erika_OS_ee.h"
#include "Erika_OS_ee_tracing.h"
#include "PWM_red.h"
#include "PWM_yellow.h"
#include "PWM_green.h"
#include "Pin_red_aliases.h"
#include "Pin_red.h"
#include "Pin_yellow_aliases.h"
#include "Pin_yellow.h"
#include "Pin_green_aliases.h"
#include "Pin_green.h"
#include "PWM_Clock.h"
#include "RGB_PWM_red.h"
#include "RGB_PWM_green.h"
#include "RGB_PWM_blue.h"
#include "RGB_R_aliases.h"
#include "RGB_R.h"
#include "RGB_G_aliases.h"
#include "RGB_G.h"
#include "RGB_B_aliases.h"
#include "RGB_B.h"
#include "RGB_PWM_Clock.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

